### ISSUE TITLE
Pay to taproot transactions can not be authored

### ISSUE THREAD

**Issue by dylan-thompson** [caravan-bitcoin/caravan#47]
Attempting to spend to a taproot address in the coordinator leads to the following error being logged to the console, and the transaction is not built.

```
Uncaught Error: tb1p62u63udffnxxuzmeltax7ydqex4adqatp528dlgwy6tjmy4vlsxq4f0qwm has no matching Script
    at Object.toOutputScript (bitcoinjs-lib.js?v=19c05fc2:1902:13)
    at _TransactionBuilder.addOutput (bitcoinjs-lib.js?v=19c05fc2:4515:35)
    at unsignedMultisigTransaction (index.mjs:5484:24)
    at finalizeOutputs (transactionReducer.js:293:27)
    at default (transactionReducer.js:426:14)
    at combination (chunk-FTCXWY4J.js?v=d49f6ef0:325:29)
    at combination (chunk-FTCXWY4J.js?v=d49f6ef0:325:29)
    at rootReducer (index.js:52:10)
    at dispatch (chunk-FTCXWY4J.js?v=d49f6ef0:174:22)
    at redux-thunk.js?v=659977c3:15:16
 ```
 
 I think bitcoinjs-lib needs updated to version 6+ 
 https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/CHANGELOG.md

**Comment by Legend101Zz** [comment]
@dylan-thompson  thanks a ton for pointing that out! 🙌
My hunch is that the issue stems from this block — though I’m not entirely certain:

```js
catch (e) {
  // Probably has an input that isn't braid-aware.
  // NOTE: This won't work for txs with taproot outputs
  unsignedTransaction = unsignedMultisigTransaction(
    state.network,
    state.inputs,
    state.outputs,
  ); // bitcoinjs-lib will throw a deprecation warning for using TransactionBuilder
}
```

You can find the context [[here](https://github.com/caravan-bitcoin/caravan/blob/main/apps/coordinator/src/reducers/transactionReducer.js#L305C5-L318C2)](https://github.com/caravan-bitcoin/caravan/blob/main/apps/coordinator/src/reducers/transactionReducer.js#L305C5-L318C2).

The root of the issue seems to be that the current `transactionReducer` is tightly coupled to an older PSBT version (from `caravan/bitcoin`) and still relies on legacy `bitcoinjs-lib` behavior.

I’m already working on updating this for #257 — aiming to properly support importing partially signed PSBTs. If this issue turns out to align with that scope, I’d be happy to bundle a fix into a follow-up PR.

@bucko13  would love to get your take — do you think this is a quick patch or does it need a broader refactor?
